# Generated by Django 5.2.4 on 2025-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='all_meanings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
