# Generated by Django 5.2.4 on 2025-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_word_all_meanings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='saved_at',
            new_name='bookmarked_at',
        ),
        migrations.RemoveField(
            model_name='word',
            name='all_meanings',
        ),
        migrations.AlterField(
            model_name='word',
            name='antonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
