# Generated by Django 5.2.4 on 2025-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_rename_saved_at_bookmark_bookmarked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='all_meanings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
