# Generated by Django 5.2.4 on 2025-07-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_word_all_meanings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='antonyms',
        ),
        migrations.RemoveField(
            model_name='word',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='word',
            name='definition_ta',
        ),
        migrations.RemoveField(
            model_name='word',
            name='example',
        ),
        migrations.RemoveField(
            model_name='word',
            name='synonyms',
        ),
        migrations.AlterField(
            model_name='word',
            name='all_meanings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
